name: Test Sync with Artifactory

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  sync:
    runs-on: App-Factory-RHEL-79

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Example call Jfrog cli
      run: jf --version

    - name: Sync changes to Artifactory
      run: |
        # Replace the placeholders with your actual values
        GITHUB_REPO_URL="https://github-us.utc.com/us-persons-only/CCOE-IaC-Templates.git"
        ARTIFACTORY_REPO_URL="https://artifactory.utc.com/ui/repos/tree/General/ccoe-usp-ccoe-iac-templates-generic-test-l"
        ARTIFACTORY_API_KEY="eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJhTkYtUFlVNUt2clRuUTRKRkdtekMwcUpwRnBGZDIwQXZmWGcwMFJZU21vIn0.eyJleHQiOiJ7XCJyZXZvY2FibGVcIjpcInRydWVcIn0iLCJzdWIiOiJqZmFjQDAxZjBmbTZxZDJ6MmttMXFxZnpiNXMxY3ZmXC91c2Vyc1wvYzk1MDM1NjcxQGFkeHVzZXIuY29tIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9uc1wvdXNlciIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDAwIiwiZXhwIjoxNzMzNTA5NTQ4LCJpYXQiOjE3MDE5NzM1NDgsImp0aSI6IjBiYmJiOTg2LTc4OTQtNDEyOS1hNzU4LTAwYzA4ZjVhYjNkOCJ9.GHR9joX8FHsyiH_KEoRJZaJZBd_YWhR31UCkrIKVsA06ntl5VnT_eOtIiL0zKgmKu1zmHETe6bJflNiHBvQpHs_3rMUF78NoJIOZvNvQhby8bAkOLioVptdhd7gFAuVpboCnOTFpPH6kVTpQijZAPxzhEIcJF2iiMhHwr1BYwfF4VlRb8Jfu827Z34SVgJYIMmHB7Gg4bvdq53RmJQp--TLQfGGAxUBczY7dPxgpVfKZ3tHZ87DsDjXz2d0IjfllbJTG080J8oGqPaKjxDtET6NXFtfHIhr-kADwHEFg4pdAs7vPTRuP1bfb2kFUNoaUdzuHTcEld_YEF0W8oefoRQ"

        # Sync changes to Artifactory
        curl -H "Authorization: Bearer $ARTIFACTORY_API_KEY" -X PUT "https://artifactory.utc.com/ui/repos/tree/General/ccoe-usp-ccoe-iac-templates-generic-test-l" -T /opt/actions-runner/_work/CCOE-IaC-Templates/AWS/main.tf -H "X-Explode-Archive:true"
      env:
        ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}