name: Sync Repositories

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Show Permissions of Repository
        run: |
           curl -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/MuhammadMesum514/testing-artifactory

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: MuhammadMesum514/testing-artifactory
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use the new secret name
          ref: master
          persist-credentials: true

      - name: Display Repository Contents
        run: |
          ls -la
          # cat hello.html

      - name: Show Changes in Source Repository
        run: |
          git status
          git diff

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          path: "dest"
          repository: MuhammadMesum514/enterprise-target
          ref: master
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use the new secret name
          persist-credentials: true

      # copy common files to new repo
      - name: Copy common files
        shell: bash
        run: |
          cp -r ./* dest/
          ls -la dest/

      # copy files from source repo to target repo
      - name: Copy files from source to target
        shell: bash
        run: |
          cp -r ./* dest/
          ls -la dest/

      - name: Sync repositories
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add enterprise-repo https://github.com/MuhammadMesum514/enterprise-target.git
          git push enterprise-repo HEAD:master
