name: Sync Repositories

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Show Permissions of Repository
        run: |
           curl -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/MuhammadMesum514/testing-artifactory

      - name: Display Repository Contents
        run: |
          ls -la
          cat README.md  # or any other file in your repository
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: MuhammadMesum514/testing-artifactory
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use the new secret name

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: MuhammadMesum514/enterprise-target
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use the new secret name

      - name: Sync repositories
        run: |
          git config --global user.name "Muhammad Mesum"
          git config --global user.email "mesumraza09@gmail.com"
          git remote add enterprise-repo git@github.com:MuhammadMesum514/enterprise-target.git
          git push enterprise-repo HEAD:master
