name: Sync Repositories

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Show Permissions of Repository
        run: |
           curl -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/MuhammadMesum514/testing-artifactory

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: MuhammadMesum514/testing-artifactory
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: master
          persist-credentials: false  # No need to persist credentials for the source repository

      - name: Display Repository Contents
        run: |
          ls -la
          # cat hello.html

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          path: "dest"
          repository: MuhammadMesum514/enterprise-target
          ref: master
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          persist-credentials: false  # No need to persist credentials for the target repository

      # - name: Copy common files
      #   run: |
      #     cp -r * dest/
      #     ls -la dest/

      - name: Copy files from source to target
        run: |
          mkdir -p dest  # Create dest directory if it doesn't exist
          ls -la 
          

      - name: Sync repositories
        run: |
          cd dest
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync changes from source repository"
          git push origin master
