name: Sync Repositories

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: MuhammadMesum514/testing-artifactory
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use the new secret name

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: MuhammadMesum514/enterprise-target
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use the new secret name

      - name: Sync repositories
        run: |
          git config --global user.name "Muhammad Mesum"
          git config --global user.email "mesumraza09@gmail.com"
          git remote add enterprise-repo git@github.com:MuhammadMesum514/enterprise-target.git
          git push enterprise-repo HEAD:master
