name: Deploy to Artifactory

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List packages
        run: ls -al

      - name: Deploy to Artifactory
        run: |
          curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }} -T hello.html "http://ec2-54-166-235-168.compute-1.amazonaws.com:8081/artifactory/test-upload/hello.html"
