name: Deploy to Artifactory

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Java
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'

      - name: Build and Publish to Artifactory
        run: |
          curl -u USERNAME:API_KEY_OR_TOKEN -T index.html "http://ec2-54-166-235-168.compute-1.amazonaws.com:8081/artifactory/test-upload/index.html"
        env:
          USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          API_KEY_OR_TOKEN: ${{ secrets.ARTIFACTORY_API_KEY }}
