name: Deploy to Artifactory

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     

      # zipping content of my repo
      - name: Zip content
        run: zip -r hello.zip .
        

      - name: List packages
        run: ls -al
        run: cat ${{ secrets.ARTIFACTORY_API_KEY }}

      # uploading zip file to artifactory
      - name: Deploy to Artifactory
        run: |
          curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }} -T hello.zip "http://ec2-54-165-221-215.compute-1.amazonaws.com:8081/artifactory/test-upload/hello.zip"

      # extracting zip file contents in artifactory
      # - name: Deploy to Artifactory
      #   run: |
      #     curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }} -T hello.zip -X POST "http://ec2-54-165-221-215.compute-1.amazonaws.com:8081/artifactory/test-upload/hello.zip?archiveType=zip&explode=1"


      # - name: Deploy to Artifactory
      #   run: |
      #     curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }} -T hello.html "http://ec2-54-165-221-215.compute-1.amazonaws.com:8081/artifactory/test-upload/hello.html"
