name: Repo Sync

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - run: git checkout -b repo-sync
      - run: git push origin repo-sync
      - uses: repo-sync/github-sync@v2
        name: Sync repo to branch
        with:
          source_repo: https://github.com/MuhammadMesum514/testing-artifactory
          source_branch: main
          destination_branch: repo-sync
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: repo-sync/pull-request@v2
        name: Create pull request
        with:
          source_branch: repo-sync
          destination_branch: main
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
