name: Push to Target Repo

on:
  push:
    branches:
      - master

jobs:
  push_to_target:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          echo ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Push to target repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "mesumraza09@gmail.com"
          git remote add target_repo https://github.com/MuhammadMesum514/enterprise-target.git
          git checkout -b repo-sync
          ls -la
          git add .
          git commit -m "Sync changes from source repo"
          git push target_repo repo-sync:main # Assuming you want to push to the 'main' branch in the target repository
