name: Push to Target Repo

on:
  push:
    branches:
      - master

jobs:
  push_to_target:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to target repo
        env:
          TARGET_REPO_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git clone https://github.com/MuhammadMesum514/enterprise-target.git
          cd enterprise-target
          git checkout master
          cp -r ../. .
          git add .
          git commit -m "Sync changes from source repo"
          git push origin master
