# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master, filter-files ]
  pull_request:
    branches: [ master, filter-files ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date in build.sh)
        run:  apk add ruby && gem install mustache
      - name: creates the wanted files in output_temp/ - example script
        run:  sh ./build.sh
      # - name: filters output_temp/ to output/ using rsync (to exclude master.epub in this example)
        # run:  apk add rsync && rsync -arv --exclude="/master.epub" output_temp/ output/
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          source-directory: output/
          destination-github-username: 'MuhammadMesum514'
          destination-repository-name: 'enterprise-target'
          user-email: mesumraza09@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY